# Generated by Django 3.2 on 2021-04-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='background_image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
