# Generated by Django 3.2 on 2021-04-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_seat_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='show_time',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
