# Generated by Django 3.2 on 2021-04-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20210418_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default='2021-03-09'),
            preserve_default=False,
        ),
    ]
